export type { SourceDocument, SourcePosition, SourceRange, SourceNodeId, SyntaxDiagnostic } from './grammar/source.js';
export { LangiumReader } from './langium/reader.js';
export type { AcceptedDocument, ReadResult } from './langium/reader.js';
export { LangiumModel } from './langium-model.js';
export { ExternalModel, ExternalInputError } from './external-model.js';
export type { ExternalDefinition, ExternalField, ExternalParameter, TypeExpression, InspectionInputProblem } from './external-model.js';
export { QueryInspection } from './query-inspection.js';
export type { Inspection } from './inspection.js';
export type { Item, Body } from './inspection-item.js';
export { QueryError, createNodeId, isNodeId } from './model.js';
export type { Model, ModelNode, ModuleModel, NodeKind, NodeId, Origin, ReferenceLookup, ReferenceResolution, CallableBody, QueryErrorCode, BuiltinName } from './model.js';
export { Resolver } from './resolution.js';
export { SourceComposer } from './source-composer.js';
export type { ModuleLocator } from './source-composer.js';
export type { Resolution, ResolutionDependencies } from './resolution.js';
export type { DeferredReference, DeferredReason } from './resolution/reference-resolver.js';
export type { ResolutionProblem, ResolutionProblemCode, ProblemLocation } from './resolution/problem.js';
export type { DependencyPackage, PackagePhase } from './resolution/package-availability.js';
export type { ErrorDescription } from './error-description.js';
export { TypeDescriber } from './type-catalog.js';
export { TypeQueryError } from './type-description.js';
export type { TypeId, TypeDescription, TypeFact, TypeProblem } from './type-description.js';
export type { TypeCatalog, TypedSlot, FieldShape, ResultDescription, CallableDescription, ConstructionDescription } from './type-catalog.js';
export { Types } from './types.js';
export { ExpressionChecker } from './expression-checker.js';
export type { ExpressionChecking, ValueScope } from './expression-checker.js';
export type { Check, Diagnostic, Requirement } from './checking.js';
export { FixtureChecker } from './fixture-checker.js';
export type { FixtureChecking } from './fixture-checker.js';
export { ScenarioChecker } from './scenario-checker.js';
export type { ScenarioChecking, ScenarioCapture, ScenarioStep } from './scenario-checker.js';
export { InteractionChecker } from './interaction-checker.js';
export type { InteractionChecking, Communication } from './interaction-checker.js';
export { Compiler } from './compiler.js';
export type { CompilationInput, Compilation, Specification } from './compiler.js';
export { ConfigurationReader } from './configuration.js';
export type { Configuration, OutputProfile, OptionProblem } from './configuration.js';
export { DependencyPlanner } from './dependency-planner.js';
export type { DependencyInventory } from './dependency-planner.js';
export { ProjectConnector } from './project-connection.js';
export { SpecificationIdentity, reconcileRelationships } from './specification-identity.js';
export type { SpecIdentifier, JsonValue, ArtifactLocator, ArtifactAssociation, IdentityRecord, IdentityBaseline, IdentityDecision, IdentifiedSpecification, SpecDiff, ObservedRelationship, RelationshipObservation, Reconciliation } from './specification-identity.js';
export type { ProjectContext, ProjectRoot, ProjectFile, ProjectSnapshot, ProjectConnection } from './project-connection.js';
export { SourceLoader, type SourceCapture, type LoadedSources, type SourceLoad } from './source-loader.js';
export { LibraryLoader, type LoadedLibraries, type LibraryLoad } from './library-loader.js';
export { NpmDependencies, type NpmOptions, type PackageRead, type PackageObservation } from './npm-dependencies.js';
export * from './project-writer.js';
export * from './output.js';
export * from './output-typescript.js';
export { acceptanceOutput } from './output-acceptance.js';
export type { ProjectRead, ProjectSearch } from './project-inspection.js';
export { TestOperationChecker, type TestOperationChecking } from './test-operation-checker.js';
export { umlOutput } from './uml-output.js';
export { TypeScriptProject, type TypeScriptProjectOptions } from './typescript-project.js';
export { TypeScriptContext } from './typescript-context.js';
export { markdownOutput } from './output-markdown.js';
export { ProjectInitializer, type InitializationPlan, type InitializationResult } from './project-initializer.js';
