export type { SourceDocument, SourcePosition, SourceRange, SourceNodeId, SyntaxDiagnostic } from './language/grammar/source.js';
export { LangiumReader } from './language/langium/reader.js';
export type { AcceptedDocument, ReadResult } from './language/langium/reader.js';
export { LangiumModel } from './model/langium-model.js';
export { ExternalModel, ExternalInputError } from './model/external-model.js';
export type { ExternalDefinition, ExternalField, ExternalParameter, TypeExpression, InspectionInputProblem } from './model/external-model.js';
export { QueryInspection } from './model/query-inspection.js';
export type { Inspection } from './model/inspection.js';
export type { Item, Body } from './model/inspection-item.js';
export { QueryError, createNodeId, isNodeId } from './model/model.js';
export type { Model, ModelNode, ModuleModel, NodeKind, NodeId, Origin, ReferenceLookup, ReferenceResolution, CallableBody, QueryErrorCode, BuiltinName } from './model/model.js';
export { Resolver } from './compiler/resolution.js';
export { SourceComposer } from './compiler/source-composer.js';
export type { ModuleLocator } from './compiler/source-composer.js';
export type { Resolution, ResolutionDependencies } from './compiler/resolution.js';
export type { DeferredReference, DeferredReason } from './compiler/resolution/reference-resolver.js';
export type { ResolutionProblem, ResolutionProblemCode, ProblemLocation } from './compiler/resolution/problem.js';
export type { DependencyPackage, PackagePhase } from './compiler/resolution/package-availability.js';
export type { ErrorDescription } from './compiler/error-description.js';
export { TypeDescriber } from './compiler/type-catalog.js';
export { TypeQueryError } from './compiler/type-description.js';
export type { TypeId, TypeDescription, TypeFact, TypeProblem } from './compiler/type-description.js';
export type { TypeCatalog, TypedSlot, FieldShape, ResultDescription, CallableDescription, ConstructionDescription } from './compiler/type-catalog.js';
export { Types } from './compiler/types.js';
export { ExpressionChecker } from './compiler/expression-checker.js';
export type { ExpressionChecking, ValueScope } from './compiler/expression-checker.js';
export type { Check, Diagnostic, Requirement } from './compiler/checking.js';
export { FixtureChecker } from './compiler/fixture-checker.js';
export type { FixtureChecking } from './compiler/fixture-checker.js';
export { ScenarioChecker } from './compiler/scenario-checker.js';
export type { ScenarioChecking, ScenarioCapture, ScenarioStep } from './compiler/scenario-checker.js';
export { InteractionChecker } from './compiler/interaction-checker.js';
export type { InteractionChecking, Communication } from './compiler/interaction-checker.js';
export { Compiler } from './compiler/compiler.js';
export type { CompilationInput, Compilation, Specification } from './compiler/compiler.js';
export { ConfigurationReader } from './project/connection/configuration.js';
export type { Configuration, OutputProfile, OptionProblem } from './project/connection/configuration.js';
export { DependencyPlanner } from './project/dependencies/dependency-planner.js';
export type { DependencyInventory } from './project/dependencies/dependency-planner.js';
export { ProjectConnector } from './project/connection/project-connection.js';
export { SpecificationIdentity, reconcileRelationships } from './model/specification-identity.js';
export type { SpecIdentifier, JsonValue, ArtifactLocator, ArtifactAssociation, IdentityRecord, IdentityBaseline, IdentityDecision, IdentifiedSpecification, SpecDiff, ObservedRelationship, RelationshipObservation, Reconciliation } from './model/specification-identity.js';
export type { ProjectContext, ProjectRoot, ProjectFile, ProjectSnapshot, ProjectConnection } from './project/connection/project-connection.js';
export { SourceLoader, type SourceCapture, type LoadedSources, type SourceLoad } from './project/connection/source-loader.js';
export { LibraryLoader, type LoadedLibraries, type LibraryLoad } from './project/dependencies/library-loader.js';
export { NpmDependencies, type NpmOptions, type PackageRead, type PackageObservation } from './project/dependencies/npm-dependencies.js';
export * from './project/connection/project-writer.js';
export * from './project/output/output.js';
export * from './project/typescript/output-typescript.js';
export { acceptanceOutput } from './project/typescript/output-acceptance.js';
export type { ProjectRead, ProjectSearch } from './project/connection/project-inspection.js';
export { TestOperationChecker, type TestOperationChecking } from './compiler/test-operation-checker.js';
export { umlOutput } from './project/output/uml-output.js';
export { TypeScriptProject, type TypeScriptProjectOptions } from './project/typescript/typescript-project.js';
export { TypeScriptContext } from './project/typescript/typescript-context.js';
export { markdownOutput } from './project/output/output-markdown.js';
export { ProjectInitializer, type InitializationPlan, type InitializationResult } from './project/connection/project-initializer.js';
export { JavaContext } from './project/java/java-context.js';
export { JavaProject } from './project/java/java-project.js';
export { javaOutput } from './project/java/output-java.js';
export { javaAcceptanceOutput } from './project/java/output-java-acceptance.js';
export { runCli, type CliOutputs } from './cli/cli.js';
