import { expect, it, onTestFinished } from 'vitest';
import { KotlinAcceptanceDriver } from '../driver/kotlin-acceptance.js';

const path = '.expec/outputs/6b6f746c696e2d616363657074616e6365.json';

/** Arranges the previous single-group ownership format using its real generated bytes and actual IDs. */
async function legacySupport(project: KotlinAcceptanceDriver) {
  const state = JSON.parse(project.files.get(path)!);
  const group = [...project.current.specification.inspection.query('examples')][0]!;
  const id = project.current.id(group.id);
  const roles = new Map([
    ['driver/ShoppingDriver.kt', { role: 'driver', name: 'ShoppingDriver' }],
    ['dsl/Shopping.kt', { role: 'dsl', name: 'Shopping' }],
    ['dsl/ShoppingFixture.kt', { role: 'fixture', name: 'ShoppingFixture' }],
    ['dsl/ExpecChecks.kt', { role: 'comparison' }],
  ]);
  for (const file of state.files) {
    const role = [...roles].find(([suffix]) => file.path.endsWith('/' + suffix))?.[1];
    if (!role) continue;
    delete file.support; file.id = id + ':' + role.role;
    file.artifacts = file.artifacts.filter((item: { specId: string }) => item.specId !== id);
    if ('name' in role) file.artifacts.unshift({ specId: id, locator: { outputId: 'kotlin-acceptance', format: 'kotlin-symbol-1',
      value: { file: file.path, declaration: [{ kind: 'class', name: role.name }] } } });
    file.artifacts.push({ specId: id, locator: { outputId: 'kotlin-acceptance', format: 'kotlin-file-1', value: { file: file.path } } });
  }
  await project.file(path, JSON.stringify(state));
  return id;
}
async function fixture() {
  const project = new KotlinAcceptanceDriver(); onTestFinished(() => project.dispose());
  await project.prepare();
  project.source('examples { observation quantity(title: Text) returns Number\nexample "one Dune": quantity("Dune") => 1 }');
  await project.generate(); expect(project.written.problems).toEqual([]);
  await project.driver('package store.tests.driver\nopen class ShoppingDriver { open fun quantity(title: String): Double = if (title == "Dune") 1.0 else 0.0 }');
  return project;
}

it('normalizes recorded single-group support while retaining its actual implementation', async () => {
  const project = await fixture(), group = await legacySupport(project);
  const before = await project.capturedFiles();
  await project.generate();
  expect(project.written.problems).toEqual([]);
  expect(project.written.artifacts?.filter(item => item.specId === group && item.locator.format === 'kotlin-symbol-1')
    .map(item => (item.locator.value as { file: string }).file)).toEqual(['src/test/kotlin/store/tests/acceptance/ShoppingAcceptance.kt']);
  expect(project.files.get('src/test/kotlin/store/tests/driver/ShoppingDriver.kt')).toBe(before.get('src/test/kotlin/store/tests/driver/ShoppingDriver.kt'));
  expect(project.files.get('src/test/kotlin/store/tests/dsl/Shopping.kt')).toBe(before.get('src/test/kotlin/store/tests/dsl/Shopping.kt'));
  expect(project.written.artifacts?.every(item => project.current.baseline.elements.some(record => record.id === item.specId))).toBe(true);
  await project.runTests();
  expect(project.compiled.code, project.compiled.stderr).toBe(0);
  expect(project.execution.code, project.execution.stderr).toBe(0);
  expect(project.outcomes.map(item => item.status)).toEqual(['passed']);
}, 240_000);

it('does not let legacy support normalization accept an altered owned DSL method', async () => {
  const project = await fixture(); await legacySupport(project);
  await project.replace('src/test/kotlin/store/tests/dsl/Shopping.kt', '= driver.quantity(title)', '= 2.0');
  const before = await project.capturedFiles();
  await project.generate();
  expect(project.written.problems.map(item => item.code)).toContain('output-conflict');
  expect(project.written.receipt).toBeUndefined();
  expect(project.files).toEqual(before);
}, 180_000);

it('does not acquire an unrelated same-named root after the recorded support root is renamed', async () => {
  const project = await fixture(); await legacySupport(project);
  await project.replace('src/test/kotlin/store/tests/driver/ShoppingDriver.kt', 'class ShoppingDriver', 'class OtherDriver');
  await project.file('src/test/kotlin/store/tests/driver/Unowned.kt', 'package store.tests.driver\nopen class ShoppingDriver { open fun quantity(title: String): Double = 1.0 }');
  const before = await project.capturedFiles();
  await project.generate();
  expect(project.written.problems.map(item => item.code)).toContain('output-conflict');
  expect(project.written.receipt).toBeUndefined();
  expect(project.files).toEqual(before);
}, 180_000);
