import { expect, it } from 'vitest';
import { Compiler, LangiumModel, LangiumReader, SourceComposer, SpecificationIdentity } from '../../src/index.js';
import { KotlinExamples } from '../../src/project/kotlin/acceptance/kotlin-examples.js';

function checked(source: string) {
  const read = new LangiumReader().read({ sourceId: 'main', text: source });
  if (read.status !== 'accepted') throw Error(JSON.stringify(read));
  const result = new Compiler().compile({ resolution: new SourceComposer().compose(new LangiumModel('main', read.document), { modules: [], packages: [] }) });
  if (!result.value) throw Error(JSON.stringify(result));
  let id = 0;
  const current = new SpecificationIdentity(() => 'acceptance-name-' + ++id).associate(result.value);
  if (!current.value) throw Error(JSON.stringify(current)); return current.value;
}

it('reports an unknown acceptance selector instead of ignoring it', () => {
  const current = checked('examples { observation quantity() returns Number\nexample "one copy": quantity() => 1 }');
  const output = new KotlinExamples(current, { testRoot: 'src/test/kotlin', package: 'store.tests', domain: 'shopping', names: [{ id: 'missing', name: 'copies' }] }, new Map());
  output.files();
  expect(output.problems).toContainEqual(expect.objectContaining({ code: 'invalid-native-mapping',
    at: { kind: 'dependency', path: ['outputs', 'kotlin-acceptance', 'missing'] } }));
});

it('refuses two native names for the same checked operation', () => {
  const current = checked('examples { observation quantity() returns Number\nexample "one copy": quantity() => 1 }');
  const operation = [...current.specification.inspection.query('observation')][0]!;
  const output = new KotlinExamples(current, { testRoot: 'src/test/kotlin', package: 'store.tests', domain: 'shopping', names: [
    { id: current.id(operation.id), name: 'copies' }, { id: current.id(operation.id), name: 'count' },
  ] }, new Map());
  output.files();
  expect(output.problems).toContainEqual(expect.objectContaining({ code: 'invalid-native-mapping', at: operation.origin }));
});

it('does not pretend an application parameter is generated by acceptance output', () => {
  const current = checked('function quantity(title: Text) returns Number');
  const parameter = [...current.specification.inspection.query('parameter')][0]!;
  const output = new KotlinExamples(current, { testRoot: 'src/test/kotlin', package: 'store.tests', domain: 'shopping', names: [
    { id: current.id(parameter.id), name: 'bookTitle' },
  ] }, new Map());
  output.files();
  expect(output.problems.map(problem => problem.code)).toContain('invalid-native-mapping');
});
